"use client"

import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/customComponents/navbar";
import Link from "next/link";
import { Poppins } from "next/font/google";
import { usePathname } from "next/navigation";

const poppins = Poppins({
  subsets: ["latin"],
  weight: "300",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body className="dark">
        <nav className='flex flex-row h-[80px] py-4 justify-around items-center border-t-0 border-l-0 border-r-0'>
          <div className="flex gap-4 items-center">
            <Link href="/">
              <h2 className={`${poppins.className} ${pathname === "/" ? "hidden" : "block"}`}>Phind</h2>
            </Link>
            {/* <Link className={`${pathname === "/" ? "block" : "hidden"}`} href="/prompt">
                          <Button variant="ghost">Chat</Button>
                       </Link>  */}
          </div>
          <ul className='flex gap-4'>
            <li><a href="#">Sign in</a></li>
            <li><a href="#">Sign up</a></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}